### ISSUE TITLE
SMPL to SMPL-X conversion: how to specify flat hand mean correctly?

### ISSUE THREAD

**Issue by kaufManu** [vchoutas/smplx#104]
I'm converting some SMPL sequences to SMPL-X (neutral) and would like to use the flat hand mean in SMPL-X since the input SMPL poses also have flat hands.

I've tried the following ways to specify this in the YAML config file:
```yaml
body_model:
    flat_hand_mean: True
```
```yaml
body_model:
    smplx:
         flat_hand_mean: True
```
However, this always resulted in (actual output differed a little bit depending on the YAML version):
```
omegaconf.errors.ConfigKeyError: Key 'flat_hand_mean' not in 'SMPLX'
        full_key: body_model.smplx.flat_hand_mean
        reference_type=SMPLX
        object_type=SMPLX
```
I've also tried this:
```
body_model:
    mano:
        hand_pose:
            pca:
                flat_hand_mean: True
```
This does not throw the above `ConfigKeyError` but I think it has no effect because the logger on line `main:55` summarizes that the SMPLXLayer does not use the flat hand mean. Hence I ended up changing `BodyModelConfig` in `body_model_defaults.py` and added the `flat_hand_mean` option like this:
```python
@dataclass
class BodyModelConfig:
    # ...
    flat_hand_mean: bool = False
```
which allowed me to use the first version of the YAML config file above. Also, the logger on line `main:55` now outputs that the flat hand mean is being used, so this seems to do what I wanted. I just wanted to confirm that this is the way to go.

Thanks!
